export interface Column {
  name: string;
  definition: string;
  autoGenerated?: boolean;
  numericType?: boolean;
  boolType?: boolean;
}

export interface Scenario {
  id: number;
  theme: string;
  company: string;
  caseStudy: string;
  dbName: string;
  tableName: string;
  columns: Column[];
  sampleData: string[][];
  selectTask: string;
}

export const scenarios: Scenario[] = [
  {
    id: 0,
    theme: 'Library Management',
    company: 'City Public Library',
    caseStudy:
      'You have been hired as a database developer for the City Public Library. They need a digital system to manage and track their entire book collection. Your task is to design and build the database from scratch using MySQL Workbench.',
    dbName: 'library_db',
    tableName: 'books',
    columns: [
      { name: 'book_id', definition: 'INT NOT NULL AUTO_INCREMENT PRIMARY KEY', autoGenerated: true, numericType: true },
      { name: 'title', definition: 'VARCHAR(100) NOT NULL' },
      { name: 'author', definition: 'VARCHAR(80) NOT NULL' },
      { name: 'genre', definition: 'VARCHAR(40)' },
      { name: 'year_published', definition: 'INT', numericType: true },
    ],
    sampleData: [
      ['The Great Gatsby', 'F. Scott Fitzgerald', 'Classic', '1925'],
      ['To Kill a Mockingbird', 'Harper Lee', 'Drama', '1960'],
      ['Harry Potter', 'J.K. Rowling', 'Fantasy', '1997'],
    ],
    selectTask: 'Retrieve all book records from the books table',
  },
  {
    id: 1,
    theme: 'Hospital Patient Records',
    company: 'Greenfield General Hospital',
    caseStudy:
      'You are a database developer for Greenfield General Hospital. The hospital needs a system to manage patient admission records. Your task is to create the database and patient table to help the hospital organise their data.',
    dbName: 'hospital_db',
    tableName: 'patients',
    columns: [
      { name: 'patient_id', definition: 'INT NOT NULL AUTO_INCREMENT PRIMARY KEY', autoGenerated: true, numericType: true },
      { name: 'full_name', definition: 'VARCHAR(100) NOT NULL' },
      { name: 'age', definition: 'INT NOT NULL', numericType: true },
      { name: 'blood_type', definition: 'VARCHAR(5)' },
      { name: 'admission_date', definition: 'DATE' },
    ],
    sampleData: [
      ['Alice Johnson', '34', 'A+', '2024-01-15'],
      ['Bob Martinez', '52', 'O-', '2024-01-17'],
      ['Carol White', '28', 'B+', '2024-01-20'],
    ],
    selectTask: 'Retrieve all patient records from the patients table',
  },
  {
    id: 2,
    theme: 'School Enrollment',
    company: 'Sunrise Academy',
    caseStudy:
      'Sunrise Academy has asked you to build a student enrollment database system. This will help the school keep track of enrolled students across different grade levels. Set up the database and the student records table.',
    dbName: 'school_db',
    tableName: 'students',
    columns: [
      { name: 'student_id', definition: 'INT NOT NULL AUTO_INCREMENT PRIMARY KEY', autoGenerated: true, numericType: true },
      { name: 'first_name', definition: 'VARCHAR(50) NOT NULL' },
      { name: 'last_name', definition: 'VARCHAR(50) NOT NULL' },
      { name: 'grade_level', definition: 'INT NOT NULL', numericType: true },
      { name: 'enrollment_date', definition: 'DATE' },
    ],
    sampleData: [
      ['Emma', 'Thompson', '9', '2024-02-01'],
      ['Liam', 'Garcia', '10', '2024-02-01'],
      ['Olivia', 'Chen', '11', '2024-02-03'],
    ],
    selectTask: 'Retrieve all enrolled student records from the students table',
  },
  {
    id: 3,
    theme: 'Online Bookstore',
    company: 'PageTurner Online Store',
    caseStudy:
      'PageTurner Online Store is launching their e-commerce platform and needs a database to manage their product catalogue. You have been tasked with setting up the initial inventory database system in MySQL.',
    dbName: 'bookstore_db',
    tableName: 'products',
    columns: [
      { name: 'product_id', definition: 'INT NOT NULL AUTO_INCREMENT PRIMARY KEY', autoGenerated: true, numericType: true },
      { name: 'product_name', definition: 'VARCHAR(100) NOT NULL' },
      { name: 'price', definition: 'DECIMAL(10,2) NOT NULL', numericType: true },
      { name: 'stock_quantity', definition: 'INT NOT NULL', numericType: true },
      { name: 'category', definition: 'VARCHAR(50)' },
    ],
    sampleData: [
      ['Clean Code', '29.99', '50', 'Technology'],
      ['Atomic Habits', '24.99', '75', 'Self-Help'],
      ['Sapiens', '19.99', '40', 'History'],
    ],
    selectTask: 'Retrieve all products from the inventory table',
  },
  {
    id: 4,
    theme: 'Hotel Reservations',
    company: 'Sunset Grand Hotel',
    caseStudy:
      'Sunset Grand Hotel is modernising their reservation system. They need a database to store guest booking details. Build the reservation database to help the hotel manage their bookings more efficiently.',
    dbName: 'hotel_db',
    tableName: 'reservations',
    columns: [
      { name: 'reservation_id', definition: 'INT NOT NULL AUTO_INCREMENT PRIMARY KEY', autoGenerated: true, numericType: true },
      { name: 'guest_name', definition: 'VARCHAR(100) NOT NULL' },
      { name: 'room_number', definition: 'INT NOT NULL', numericType: true },
      { name: 'check_in_date', definition: 'DATE NOT NULL' },
      { name: 'total_nights', definition: 'INT NOT NULL', numericType: true },
    ],
    sampleData: [
      ['David Kim', '201', '2024-03-10', '3'],
      ['Sarah Brown', '105', '2024-03-12', '5'],
      ['Michael Lee', '310', '2024-03-15', '2'],
    ],
    selectTask: 'Retrieve all reservation records from the reservations table',
  },
  {
    id: 5,
    theme: 'Restaurant Menu',
    company: 'The Spice Garden Restaurant',
    caseStudy:
      'The Spice Garden Restaurant wants to digitalise their menu management system. They need a database to store all menu items, prices, and availability status. Help them build a structured database from scratch.',
    dbName: 'restaurant_db',
    tableName: 'menu_items',
    columns: [
      { name: 'item_id', definition: 'INT NOT NULL AUTO_INCREMENT PRIMARY KEY', autoGenerated: true, numericType: true },
      { name: 'item_name', definition: 'VARCHAR(80) NOT NULL' },
      { name: 'price', definition: 'DECIMAL(8,2) NOT NULL', numericType: true },
      { name: 'category', definition: 'VARCHAR(40) NOT NULL' },
      { name: 'is_available', definition: 'BOOLEAN DEFAULT TRUE', boolType: true },
    ],
    sampleData: [
      ['Grilled Chicken', '18.50', 'Main Course', 'TRUE'],
      ['Caesar Salad', '12.00', 'Starter', 'TRUE'],
      ['Chocolate Lava Cake', '9.50', 'Dessert', 'FALSE'],
    ],
    selectTask: 'Retrieve all menu items from the menu_items table',
  },
  {
    id: 6,
    theme: 'Employee Management',
    company: 'TechCorp Ltd.',
    caseStudy:
      'TechCorp Ltd. is building an internal HR system and needs a database to manage their employee records. You have been brought in to design and implement the initial employee database in MySQL.',
    dbName: 'company_db',
    tableName: 'employees',
    columns: [
      { name: 'employee_id', definition: 'INT NOT NULL AUTO_INCREMENT PRIMARY KEY', autoGenerated: true, numericType: true },
      { name: 'full_name', definition: 'VARCHAR(100) NOT NULL' },
      { name: 'department', definition: 'VARCHAR(60) NOT NULL' },
      { name: 'salary', definition: 'DECIMAL(10,2) NOT NULL', numericType: true },
      { name: 'hire_date', definition: 'DATE' },
    ],
    sampleData: [
      ['James Wilson', 'Engineering', '85000.00', '2021-06-15'],
      ['Priya Patel', 'Marketing', '72000.00', '2022-01-10'],
      ['Ryan Nguyen', 'Human Resources', '68000.00', '2020-09-01'],
    ],
    selectTask: 'Retrieve all employee records from the employees table',
  },
  {
    id: 7,
    theme: 'Student Grade Tracker',
    company: 'Wellington Tech Institute',
    caseStudy:
      'Wellington Tech Institute needs a database to record and track student academic results. You are tasked with creating the database system that will store examination scores and grades for all students.',
    dbName: 'grades_db',
    tableName: 'results',
    columns: [
      { name: 'result_id', definition: 'INT NOT NULL AUTO_INCREMENT PRIMARY KEY', autoGenerated: true, numericType: true },
      { name: 'student_name', definition: 'VARCHAR(100) NOT NULL' },
      { name: 'subject', definition: 'VARCHAR(60) NOT NULL' },
      { name: 'score', definition: 'INT NOT NULL', numericType: true },
      { name: 'grade', definition: 'VARCHAR(2) NOT NULL' },
    ],
    sampleData: [
      ['Amy Foster', 'Mathematics', '88', 'B+'],
      ['Jake Rivera', 'Physics', '95', 'A'],
      ['Nina Okafor', 'Chemistry', '74', 'B-'],
    ],
    selectTask: 'Retrieve all student result records from the results table',
  },
  {
    id: 8,
    theme: 'Gym Membership',
    company: 'FitLife Gym',
    caseStudy:
      'FitLife Gym is expanding and needs a database to track member subscriptions. Your job is to create a membership management database that stores member details and subscription fee information.',
    dbName: 'gym_db',
    tableName: 'members',
    columns: [
      { name: 'member_id', definition: 'INT NOT NULL AUTO_INCREMENT PRIMARY KEY', autoGenerated: true, numericType: true },
      { name: 'member_name', definition: 'VARCHAR(100) NOT NULL' },
      { name: 'membership_type', definition: 'VARCHAR(30) NOT NULL' },
      { name: 'start_date', definition: 'DATE NOT NULL' },
      { name: 'monthly_fee', definition: 'DECIMAL(8,2) NOT NULL', numericType: true },
    ],
    sampleData: [
      ['Chris Evans', 'Premium', '2024-01-01', '79.99'],
      ['Mia Santos', 'Basic', '2024-02-01', '39.99'],
      ['Omar Hassan', 'Premium', '2024-01-15', '79.99'],
    ],
    selectTask: 'Retrieve all gym member records from the members table',
  },
  {
    id: 9,
    theme: 'Car Rental Fleet',
    company: 'DriveEasy Car Rentals',
    caseStudy:
      'DriveEasy Car Rentals is building a fleet management system. They need a database to track all vehicles in their rental fleet. Create the database and vehicle table to help them manage their fleet effectively.',
    dbName: 'rental_db',
    tableName: 'vehicles',
    columns: [
      { name: 'vehicle_id', definition: 'INT NOT NULL AUTO_INCREMENT PRIMARY KEY', autoGenerated: true, numericType: true },
      { name: 'make', definition: 'VARCHAR(50) NOT NULL' },
      { name: 'model', definition: 'VARCHAR(50) NOT NULL' },
      { name: 'year', definition: 'INT NOT NULL', numericType: true },
      { name: 'daily_rate', definition: 'DECIMAL(8,2) NOT NULL', numericType: true },
    ],
    sampleData: [
      ['Toyota', 'Camry', '2022', '65.00'],
      ['Honda', 'Civic', '2023', '58.00'],
      ['Ford', 'Mustang', '2021', '95.00'],
    ],
    selectTask: 'Retrieve all vehicles from the vehicles table',
  },
];

export function buildCreateTableSql(s: Scenario): string {
  const cols = s.columns.map(c => `  ${c.name} ${c.definition}`).join(',\n');
  return `USE ${s.dbName};\n\nCREATE TABLE ${s.tableName} (\n${cols}\n);`;
}

export function buildInsertSql(s: Scenario): string {
  const insertCols = s.columns.filter(c => !c.autoGenerated);
  const colNames = insertCols.map(c => c.name).join(', ');
  const rows = s.sampleData.map(row => {
    const vals = row.map((v, i) => {
      const col = insertCols[i];
      if (col.numericType || col.boolType) return v;
      return `'${v}'`;
    });
    return `  (${vals.join(', ')})`;
  });
  return `USE ${s.dbName};\n\nINSERT INTO ${s.tableName} (${colNames})\nVALUES\n${rows.join(',\n')};`;
}

export function buildSelectSql(s: Scenario): string {
  return `USE ${s.dbName};\n\nSELECT * FROM ${s.tableName};`;
}
